dist: trusty
sudo: false

language: C


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code